# Generated by Django 3.0.2 on 2020-02-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200222_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=models.SET(-1), related_name='+', to='api.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=models.SET(-1), related_name='+', to='api.StoreItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
