# Generated by Django 3.0.2 on 2020-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200222_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='product',
            new_name='store_item',
        ),
        migrations.RenameField(
            model_name='transactionitem',
            old_name='product_name',
            new_name='store_item_name',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
