# Generated by Django 3.0.2 on 2020-05-16 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200516_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
