# Generated by Django 3.0.2 on 2020-05-16 12:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_transaction_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
