# Generated by Django 3.0.2 on 2020-05-16 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200516_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
