# Generated by Django 3.0.2 on 2020-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200517_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='reset_pass',
            field=models.BooleanField(default=False),
        ),
    ]
