# Generated by Django 3.0.2 on 2020-05-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='storechain',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/store_chains'),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('store_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promos', to='api.StoreChain')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.FloatField()),
                ('store_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='discount', to='api.StoreItem')),
            ],
        ),
    ]
