# Generated by Django 3.0.2 on 2021-05-15 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200524_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
                ('description', models.CharField(max_length=150)),
                ('conditions', models.CharField(max_length=100)),
                ('store_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partnercampaign_promo_campaign', to='api.StoreChain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaidCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
                ('description', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('store_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paidcampaign_promo_campaign', to='api.StoreChain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
